### ISSUE TITLE
Genotype pending database transactions cause the webui to crash

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/genotype-api#148]
Reported by @eliottBo
Hello, I am trying to upload a MAF plate to genotype but I get this can I have some help? (my VPN is working fine for the rest)

![image](https://github.com/user-attachments/assets/d1546d59-09b7-4455-8c05-9311bd5fc678)

**Comment by seallard** [comment]
```
Jul 18 13:35:46 cg-services-prod.scilifelab.se podman[874142]: 130.237.81.17 - - [18/Jul/2024:13:35:46 +0200] "POST /reports/report HTTP/1.0" 200 28979 "-" "python-requests/2.32.3"
...skipping...
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/home/worker/app/genotype_api/database/crud/read.py", line 88, in get_plate_by_plate_id
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     db_plate = self.store.get_plate_by_plate_id(plate_id)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/home/worker/app/genotype_api/services/endpoint_services/plate_service.py", line 75, in upload_plate
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     plate_service.upload_plate(file)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/home/worker/app/genotype_api/api/endpoints/plates.py", line 35, in upload_plate
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:              ^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     result = context.run(func, *args)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:            ^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     return await future
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     return await get_async_backend().run_sync_in_worker_thread(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     return await anyio.to_thread.run_sync(func, *args)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     return await run_in_threadpool(dependant.call, **values)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     raw_response = await run_endpoint_function(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:                ^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     response = await func(request)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await app(scope, receive, sender)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.app(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await route.handle(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.middleware_stack(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await app(scope, receive, sender)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.app(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.simple_response(scope, receive, send, request_headers=headers)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.app(scope, receive_or_disconnect, send_no_error)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     raise app_exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     response = await call_next(request)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/home/worker/app/genotype_api/api/middleware.py", line 11, in dispatch
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     response = await self.dispatch_func(request, call_next)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     self.gen.throw(typ, value, traceback)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     with collapse_excgroups():
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.app(scope, receive, _send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await self.middleware_stack(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     await super().__call__(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     return await self.app(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     result = await app(  # type: ignore[func-returns-value]
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]: Traceback (most recent call last):
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]: During handling of the above exception, another exception occurred:
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     +------------------------------------
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     | sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proc>
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raise exc.PendingRollbackError(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 671, in _invalid_transaction
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     self._invalid_transaction()
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 681, in _revalidate_connection
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     conn = self._revalidate_connection()
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1817, in _execute_context
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |           ^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     ret = self._execute_context(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return connection._execute_clauseelement(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return meth(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |              ^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     result = conn.execute(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     result: Result[Any] = compile_state_cls.orm_execute_statement(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return self._execute_internal(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                                                   ^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return self.limit(1)._iter().first()  # type: ignore
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2728, in first
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |       ^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     ).first()
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/home/worker/app/genotype_api/database/crud/read.py", line 88, in get_plate_by_plate_id
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     db_plate = self.store.get_plate_by_plate_id(plate_id)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/home/worker/app/genotype_api/services/endpoint_services/plate_service.py", line 75, in upload_plate
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     plate_service.upload_plate(file)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/home/worker/app/genotype_api/api/endpoints/plates.py", line 35, in upload_plate
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |              ^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     result = context.run(func, *args)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return await future
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return await get_async_backend().run_sync_in_worker_thread(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return await anyio.to_thread.run_sync(func, *args)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return await run_in_threadpool(dependant.call, **values)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raw_response = await run_endpoint_function(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                ^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     response = await func(request)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await app(scope, receive, sender)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.app(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await route.handle(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.middleware_stack(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await app(scope, receive, sender)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.app(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.simple_response(scope, receive, send, request_headers=headers)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.app(scope, receive_or_disconnect, send_no_error)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raise app_exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     response = await call_next(request)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/home/worker/app/genotype_api/api/middleware.py", line 11, in dispatch
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     response = await self.dispatch_func(request, call_next)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     self.gen.throw(typ, value, traceback)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     with collapse_excgroups():
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.app(scope, receive, _send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     raise exc
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await self.middleware_stack(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     await super().__call__(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     return await self.app(scope, receive, send)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |     result = await app(  # type: ignore[func-returns-value]
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:     | Traceback (most recent call last):
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   +-+---------------- 1 ----------------
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   |     raise BaseExceptionGroup(
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   |     async with anyio.create_task_group() as task_group:
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   |     yield
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]:   + Exception Group Traceback (most recent call last):
Jul 18 13:32:39 cg-services-prod.scilifelab.se podman[1822745]: [2024-07-18 13:32:39 +0200] [11] [ERROR] Exception in ASGI application
```

**Comment by seallard** [comment]
Current fix: restart service with
```
sudo -iu hiseq.clinical
ssh localhost
systemctl --user list-dependencies everything.target
systemctl --user restart genotype-api@v3.0.16.service
```

**Comment by Vince-janv** [comment]
I thought i fixed and deployed this in version v3.0.17. Strange that the container running on the VM was v3.0.16 🤔

**Comment by Vince-janv** [comment]
Turns out the deploy action is broken for the repo...

**Comment by seallard** [comment]
Deployments have been patched by @Vince-janv

**Comment by eliottBo** [comment]
Seems that the problem persists: 
<img width="477" alt="Screenshot 2024-07-25 at 08 33 55" src="https://github.com/user-attachments/assets/4c4838c4-680d-45fa-a6b3-9a07a1706d8b">

**Comment by seallard** [comment]
Me and @islean looked into this a bit more.

When you visit the genotype app in cigrid, a lot of sleeping process are created and remain when you show the processes in the database. However, we added application level logging which tells us that the tear down is actually run per request. So the connections should be released.

Our hypothesis was that the teardown was not being run, causing a lot of connections to remain open and then causing meta data lock contention and somehow crashing the application. However, since the teardown is being run per request - this does not seem to be the case.

**Comment by ChrOertlin** [comment]
We likely need to enable logging on the mysql server to get more info on these sleeping processes I think. That requires a mysql server restart however. @Vince-janv can we do that?

**Comment by Vince-janv** [comment]
Are these settings that are changed via the mysql CLI? If so I think we should be able to do it since we have access to the root mysql user

**Comment by ChrOertlin** [comment]
I checked and the services-prod mysql server instance does not point to a config file. However, we need to enable logging via a config file. For these then to take effect we need to restart the mysql server instance. I am not sure to what extent that will disrupt prod.

**Comment by seallard** [comment]
Could it be that there is some other package which interacts with the genotype database and does not clean up the connections properly?

**Comment by ChrOertlin** [comment]
Yes there is the genotye upload command from the genotype repo that CG calls. It might be that since we altered the session handling that now it doesn't work properly anymore. But I am unsure, that is why I thought the logs could help to see where these sleeping connections come from.

**Comment by ChrOertlin** [comment]
`"""Interactions with the genotype tool"""

import logging

from cg.exc import CaseNotFoundError
from cg.utils.commands import Process

LOG = logging.getLogger(__name__)


class GenotypeAPI:
    """Interface with Genotype app.

    The config should contain a 'genotype' key:

        { 'database': 'mysql://localhost:3306/database' }
    """

    def __init__(self, config: dict):
        self.process = Process(
            binary=config["genotype"]["binary_path"], config=config["genotype"]["config_path"]
        )
        self.dry_run = False

    def set_dry_run(self, dry_run: bool) -> None:
        """Set the dry run state"""
        self.dry_run = dry_run

    def upload(self, bcf_path: str, samples_sex: dict, force: bool = False) -> None:
        """Upload genotypes for a family of samples."""
        upload_parameters = ["load", str(bcf_path)]
        if force:
            upload_parameters.append("--force")

        LOG.info(f"loading VCF genotypes for sample(s): {', '.join(samples_sex.keys())}")
        self.process.run_command(parameters=upload_parameters, dry_run=self.dry_run)

        for sample_id in samples_sex:
            # This is the sample sex specified by the customer
            sample_sex = samples_sex[sample_id]["pedigree"]
            self.update_sample_sex(sample_id, sample_sex)
            # This is the predicted sex based on variant calls from the workflow
            analysis_predicted_sex = samples_sex[sample_id]["analysis"]
            self.update_analysis_sex(sample_id, sex=analysis_predicted_sex)

    def update_sample_sex(self, sample_id: str, sex: str) -> None:
        """Update the sex for a sample in the genotype tool"""
        sample_sex_parameters = ["add-sex", sample_id, "-s", sex]
        LOG.debug(f"Set sex for sample {sample_id} to {sex}")
        self.process.run_command(parameters=sample_sex_parameters, dry_run=self.dry_run)

    def update_analysis_sex(self, sample_id: str, sex: str) -> None:
        """Update the predicted sex for a sample based on genotype analysis in the genotype tool"""
        analysis_sex_parameters = ["add-sex", sample_id, "-a", "sequence", sex]
        LOG.debug(f"Set predicted sex for sample {sample_id} to {sex} for the sequence analysis")
        self.process.run_command(parameters=analysis_sex_parameters, dry_run=self.dry_run)

    def export_sample(self, days: int = 0) -> str:
        """Export sample info."""
        export_sample_parameters = ["export-sample", "-d", str(days)]

        self.process.run_command(parameters=export_sample_parameters, dry_run=self.dry_run)
        output = self.process.stdout
        # If sample not in genotype db, stdout of genotype command will be empty.
        if not output:
            raise CaseNotFoundError("samples not found in genotype db")
        return output

    def export_sample_analysis(self, days: int = 0) -> str:
        """Export analysis."""
        export_sample_analysis_parameters = ["export-sample-analysis", "-d", str(days)]

        self.process.run_command(parameters=export_sample_analysis_parameters, dry_run=self.dry_run)
        output = self.process.stdout
        # If sample not in genotype db, stdout of genotype command will be empty.
        if not output:
            raise CaseNotFoundError("samples not found in genotype db")
        return output

    def __str__(self):
        return f"GenotypeAPI(dry_run: {self.dry_run})"
`

**Comment by Vince-janv** [comment]
Regarding enabling logging, how do we prevent the logs from growing out of hand? Are there settings to only save the latest XX Gb of logs?

**Comment by islean** [comment]
> Yes there is the genotye upload command from the genotype repo that CG calls (note, this is not the genotype-api repo). It might be that since we altered the session handling that now it doesn't work properly anymore. But I am unsure, that is why I thought the logs could help to see where these sleeping connections come from.

That does not sound as if it should be invoked when you go to the genotype tab in cigrid though? I would wager that this is not in cg since I am pretty certain that CiGRID sends its requests directly to the genotype-api.

**Comment by ChrOertlin** [comment]
Yes, @islean there is anther command run in CG that makes these genotype cli commands. We need to see if there is something in the genotype (NOT genotype-API) repo that needs fixing is my guess.

**Comment by islean** [comment]
> Yes, @islean there is anther command run in CG that makes these genotype cli commands. We need to see if there is something in the genotype (NOT genotype-API) repo that needs fixing is my guess.

Good point! Does genotype api interact with genotype as well? Or is this just on top of the genotype-api issue? I.e. when you interact with genotype-api in CiGRID you can open the process list in MySQL and see that there are sessions created which are not closed even when closing your browser.

**Comment by Vince-janv** [comment]
Blocked by: https://github.com/Clinical-Genomics/cg/issues/2576

**Comment by ahdamin** [comment]
When the database server connection is lost, a `BrokenPipeError` is raised. After this, any attempt by the Sample Service to access the database results in a `PendingRollbackError` due to the invalid session. [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/20/core/pooling.html#setting-pool-recycle) suggests that setting the `pool_recycle` parameter can prevent the connection pool from using stale connections that have exceeded a certain age. Check the [PR](https://github.com/Clinical-Genomics/genotype-api/pull/150)

**Comment by ahdamin** [comment]
Deployed to `cg-services-prod`:

```
[hiseq.clinical@cg-services-prod servers]$ systemctl --user status genotype-api@v3.0.19.service
● genotype-api@v3.0.19.service - Genotype-api
   Loaded: loaded (/home/hiseq.clinical/.config/systemd/user/genotype-api@.service; disabled; vendor preset: enabled)
   Active: active (running) since Tue 2024-10-15 01:16:18 CEST; 8s ago
  Process: 2926230 ExecStopPost=/usr/bin/podman rm genotype-api-v3.0.19 (code=exited, status=0/SUCCESS)
  Process: 2926194 ExecStop=/usr/bin/podman stop genotype-api-v3.0.19 (code=exited, status=0/SUCCESS)
  Process: 2926241 ExecStartPre=/usr/bin/podman pull ${CONTAINER_URL}:v3.0.19 (code=exited, status=0/SUCCESS)
 Main PID: 2926255 (podman)
   CGroup: /user.slice/user-2191.slice/user@2191.service/genotype\x2dapi.slice/genotype-api@v3.0.19.service
           ├─2926255 /usr/bin/podman run --expose 25000 --security-opt label=disable --env-file /var/cg-data/container-env//genotype-api.env --replace --i>
           ├─2926292 /usr/bin/fuse-overlayfs -o lowerdir=/home/hiseq.clinical/.local/share/containers/storage/overlay/l/CGFCPJRTJI2YCDJ2UTB35BW2ZT:/home/h>
           ├─2926295 /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp --enable-ipv6 -c -r 3 -e 4 --netns-type=pa>
           ├─2926297 rootlessport
           ├─2926303 rootlessport-child
           ├─2926312 /usr/bin/conmon --api-version 1 -c 059ab997caaacae2ce8c8b79c31f6555da04da0407a7fcd91e72ced3cf9e2d37 -u 059ab997caaacae2ce8c8b79c31f65>
           └─059ab997caaacae2ce8c8b79c31f6555da04da0407a7fcd91e72ced3cf9e2d37
             ├─2926323 /run/podman-init -- /bin/sh -c gunicorn     --workers=$GUNICORN_WORKERS     --bind=$GUNICORN_BIND      --threads=$GUNICORN_THREADS >
             ├─2926335 /bin/sh -c gunicorn     --workers=$GUNICORN_WORKERS     --bind=$GUNICORN_BIND      --threads=$GUNICORN_THREADS     --timeout=$GUNIC>
             ├─2926336 /usr/local/bin/python3.11 /usr/local/bin/gunicorn --workers=4 --bind=0.0.0.0:8000 --threads=4 --timeout=400 --proxy-protocol --forw>
             ├─2926337 /usr/local/bin/python3.11 /usr/local/bin/gunicorn --workers=4 --bind=0.0.0.0:8000 --threads=4 --timeout=400 --proxy-protocol --forw>
             ├─2926338 /usr/local/bin/python3.11 /usr/local/bin/gunicorn --workers=4 --bind=0.0.0.0:8000 --threads=4 --timeout=400 --proxy-protocol --forw>
             ├─2926339 /usr/local/bin/python3.11 /usr/local/bin/gunicorn --workers=4 --bind=0.0.0.0:8000 --threads=4 --timeout=400 --proxy-protocol --forw>
             └─2926340 /usr/local/bin/python3.11 /usr/local/bin/gunicorn --workers=4 --bind=0.0.0.0:8000 --threads=4 --timeout=400 --proxy-protocol --forw>

Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [10] [INFO] Application startup complete.
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [9] [INFO] Started server process [9]
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [9] [INFO] Waiting for application startup.
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [11] [INFO] Started server process [11]
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [9] [INFO] Application startup complete.
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [11] [INFO] Waiting for application startup.
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [11] [INFO] Application startup complete.
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [12] [INFO] Started server process [12]
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [12] [INFO] Waiting for application startup.
Oct 15 01:16:24 cg-services-prod.scilifelab.se podman[2926255]: [2024-10-15 01:16:24 +0200] [12] [INFO] Application startup complete.
```
